#ifndef EPlanet_H
#define EPlanet_H

enum EPlanet
{
    EPLANET_MERKUR,
    EPLANET_VENUS,
    EPLANET_ERDE,
    EPLANET_MARS,
    EPLANET_JUPITER,
    EPLANET_SATURN,
    EPLANET_URANUS,
    EPLANET_NEPTUN,
    EPLANET_SONNE,
    EMOND_GANYMED,
    EMOND_EUROPA,
    EMOND_KALLISTO,
    EMOND_IO,
    EMOND_MOND,
    EMOND_TITAN,
    EMOND_RHEA,
    EMOND_TRITON
};

#endif
