LIBFILES = $(LIBBASE)/CG3DReslistInterface.cpp \
           $(LIBBASE)/CGL_Patch.cpp \
           $(LIBBASE)/CGL_Ellipsoid.cpp \
           $(LIBBASE)/CG3DResource.cpp \
           $(LIBBASE)/CG3DResourceImgRef.cpp \
           $(LIBBASE)/CG3DResourceButton.cpp \
           $(LIBBASE)/CG3DResourceOButton.cpp \
           $(LIBBASE)/CG3DResourceList.cpp \
           $(LIBBASE)/CG3DResourceDialog.cpp \
           $(LIBBASE)/CG3DResourceImage.cpp \
           $(LIBBASE)/CG3DResourceString.cpp \
	   $(LIBBASE)/CG3DResourceFont.cpp \
           $(LIBBASE)/CG3DResourceLine.cpp \
           $(LIBBASE)/CG3DResourceBox.cpp \
           $(LIBBASE)/CG3DResourceRoot.cpp \
           $(LIBBASE)/CG3DResourceTextfield.cpp \
           $(LIBBASE)/CG3DResourceTooltipp.cpp \
           $(LIBBASE)/CG3DResourceClipframe.cpp \
           $(LIBBASE)/CG3DResChild.cpp \
           $(LIBBASE)/CTagList.cpp \
           $(LIBBASE)/CErrorMessage.cpp \
           $(LIBBASE)/CPixel24.cpp \
		   $(LIBBASE)/CPixel32.cpp \
           $(LIBBASE)/CDatabase3.cpp \
           $(LIBBASE)/CFileIO.cpp \
           $(LIBBASE)/CGraflib.cpp \
           $(LIBBASE)/CGraflibTga.cpp \
           $(LIBBASE)/CGraflibJpeg.cpp \
           $(LIBBASE)/CGraphicsJpeg.cpp \
           $(LIBBASE)/CGL_MatObject.cpp \
           $(LIBBASE)/CGL_Texture.cpp \
           $(LIBBASE)/COpenGL.cpp \
           $(LIBBASE)/CGL_Camera.cpp \
           $(LIBBASE)/CGL_Object.cpp \
           $(LIBBASE)/CGL_Disk.cpp \
           $(LIBBASE)/CGL_GLU_Object.cpp \
           $(LIBBASE)/CGL_GLU_Sphere.cpp \
           $(LIBBASE)/CGL_FontTableau.cpp \
           $(LIBBASE)/CGL_Circle.cpp \
           $(NULL)
